---
title: "Assignment 6"
author: "msasnur@kent.edu"
date: "04/11/2019"
output:
  word_document: default
  html_document: default
---

```{r}
library(lpSolveAPI)
library(Benchmarking)
library(ucminf)
```
Question 1

DMU 1

Max, z= 14000 u1 + 3500 u2

Subject to constraints,

14000 u1 + 3500 u2 – 150 v1 – 0.2 v2 <= 0

14000 u1 + 21000 u2 – 400 v1 – 0.7 v2 <= 0

42000 u1 + 10500 u2 – 320 v1 – 1.2 v2 <= 0

28000 u1 + 42000 u2 – 520 v1 – 2.0 v2 <= 0

19000 u1 + 25000 u2 – 350 v1 – 1.2 v2 <= 0

14000 u1 + 15000 u2 – 320 v1 – 0.7 v2 <= 0

150 v1 + 0.2 v2 = 1

v1, v2, u1, u2, >=0

```{r}
lpdea1<-make.lp(0,4)
lp.control(lpdea1,sense="max")
set.objfn(lpdea1,c(0,0,14000,3500))
# Constraints for Facility 1
add.constraint(lpdea1,c(-150,-0.2,14000,3500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea1,c(-400,-0.7,14000,21000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea1,c(-320,-1.2,42000,10500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea1,c(-520,-2.0,28000,42000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea1,c(-350,-1.2,19000,25000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea1,c(-320,-0.7,14000,15000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea1,c(150,0.2),"=",1,indices = c(1,2))
solve(lpdea1)
get.objective(lpdea1)
get.variables(lpdea1)
#Here the objective value is 1, which indicates that we can achieve maximum efficiency from DMU(1).
#This happens when we use the weights 0 and 0.00714 for the outputs, 0.5172414 and 1.12069 for the input.
```
DMU 2

Max, z= 14000 u1 + 21000 u2

Subject to constraints,

14000 u1 + 3500 u2 – 150 v1 – 0.2 v2 <= 0

14000 u1 + 21000 u2 – 400 v1 – 0.7 v2 <= 0

42000 u1 + 10500 u2 – 320 v1 – 1.2 v2 <= 0

28000 u1 + 42000 u2 – 520 v1 – 2.0 v2 <= 0

19000 u1 + 25000 u2 – 350 v1 – 1.2 v2 <= 0

14000 u1 + 15000 u2 – 320 v1 – 0.7 v2 <= 0

400 v1 + 0.7 v2 = 1

v1, v2, u1, u2, >=0


```{r}
lpdea2<-make.lp(0,4)
lp.control(lpdea2,sense="max")
set.objfn(lpdea2,c(0,0,14000,21000))
#Constraints for Facility 2
add.constraint(lpdea2,c(-400,-0.7,14000,21000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea2,c(-150,-0.2,14000,3500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea2,c(-320,-1.2,42000,10500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea2,c(-520,-2.0,28000,42000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea2,c(-350,-1.2,19000,25000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea2,c(-320,-0.7,14000,15000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea2,c(400,0.7),"=",1,indices = c(1,2))
solve(lpdea2)
get.objective(lpdea2)
get.variables(lpdea2)
#Here the objective value is 1, which indicates that we can achieve maximum efficiency for DMU(2). 
#This happens when we use the weights 0 and 0.00476 for the outputs, 0.1376147 and 0.6422 for the input.
```
DMU 3

Max, z= 42000 u1 + 10500 u2

Subject to constraints,

14000 u1 + 3500 u2 – 150 v1 – 0.2 v2 <= 0

14000 u1 + 21000 u2 – 400 v1 – 0.7 v2 <= 0

42000 u1 + 10500 u2 – 320 v1 – 1.2 v2 <= 0

28000 u1 + 42000 u2 – 520 v1 – 2.0 v2 <= 0

19000 u1 + 25000 u2 – 350 v1 – 1.2 v2 <= 0

14000 u1 + 15000 u2 – 320 v1 – 0.7 v2 <= 0

320 v1 + 1.2 v2 = 1

v1, v2, u1, u2, >=0


```{r}
lpdea3<-make.lp(0,4)
lp.control(lpdea3,sense="max")
set.objfn(lpdea3,c(0,0,42000,10500))
# Constraints for Facility 3
add.constraint(lpdea3,c(-400,-0.7,14000,21000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea3,c(-150,-0.2,14000,3500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea3,c(-320,-1.2,42000,10500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea3,c(-520,-2.0,28000,42000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea3,c(-350,-1.2,19000,25000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea3,c(-320,-0.7,14000,15000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea3,c(320,1.2),"=",1,indices = c(1,2))
solve(lpdea3)
get.objective(lpdea3)
get.variables(lpdea3)
#Here the objective value is 1, which indicates that we can achieve maximum efficiency for DMU(3). 
#This happens when we use the weights 0 and 0.00238 for the outputs, 0.001724 and 0.3735 for the input.
```
DMU 4:
Max, z= 28000 u1 + 42000 u2

Subject to constraints,

14000 u1 + 3500 u2 – 150 v1 – 0.2 v2 <= 0

14000 u1 + 21000 u2 – 400 v1 – 0.7 v2 <= 0

42000 u1 + 10500 u2 – 320 v1 – 1.2 v2 <= 0

28000 u1 + 42000 u2 – 520 v1 – 2.0 v2 <= 0

19000 u1 + 25000 u2 – 350 v1 – 1.2 v2 <= 0

14000 u1 + 15000 u2 – 320 v1 – 0.7 v2 <= 0

520 v1 + 2.0 v2 = 1
v1, v2, u1, u2, >=0

```{r}
lpdea4<-make.lp(0,4)
lp.control(lpdea4,sense="max")
set.objfn(lpdea4,c(0,0,28000,42000))

#Constraints for Facility 4
add.constraint(lpdea4,c(-400,-0.7,14000,21000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea4,c(-150,-0.2,14000,3500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea4,c(-320,-1.2,42000,10500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea4,c(-520,-2.0,28000,42000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea4,c(-350,-1.2,19000,25000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea4,c(-320,-0.7,14000,15000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea4,c(520,2.0),"=",1,indices = c(1,2))
solve(lpdea4)
get.objective(lpdea4)
get.variables(lpdea4)
#The solution indicates that the objective value is 1, which indicates that we can achieve maximum efficiency for DMU(4).
#This happens when we use the weights 0 and 0.00238 for the outputs, 0.0688 and 0.3211 for the input.
```
DMU 5

Max, z= 19000 u1 + 25000 u2

Subject to constraints,

14000 u1 + 3500 u2 – 150 v1 – 0.2 v2 <= 0

14000 u1 + 21000 u2 – 400 v1 – 0.7 v2 <= 0

42000 u1 + 10500 u2 – 320 v1 – 1.2 v2 <= 0

28000 u1 + 42000 u2 – 520 v1 – 2.0 v2 <= 0

19000 u1 + 25000 u2 – 350 v1 – 1.2 v2 <= 0

14000 u1 + 15000 u2 – 320 v1 – 0.7 v2 <= 0

350 v1 + 1.2 v2 = 1

v1, v2, u1, u2, >=0

```{r}

lpdea5<-make.lp(0,4)
lp.control(lpdea5,sense="max")
set.objfn(lpdea5,c(0,0,19000,25000))

# Constraints for Facility 5
add.constraint(lpdea5,c(-400,-0.7,14000,21000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea5,c(-150,-0.2,14000,3500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea5,c(-320,-1.2,42000,10500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea5,c(-520,-2.0,28000,42000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea5,c(-350,-1.2,19000,25000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea5,c(-320,-0.7,14000,15000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea5,c(350,1.2),"=",1,indices = c(1,2))
solve(lpdea5)
get.objective(lpdea5)
get.variables(lpdea5)
#Here the objective value is 0.9775, which indicates that we are not able to achieve maximum efficiency for DMU(5). 
#This happens when we use the weights 0.00001151 and 0.000030350 for the outputs, 0.001098 and 0.5128 for the input. 

##DMU 6
lpdea6<-make.lp(0,4)
lp.control(lpdea6,sense="max")
set.objfn(lpdea6,c(0,0,14000,15000))
# Constraints for Facility 6
add.constraint(lpdea6,c(-400,-0.7,14000,21000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea6,c(-150,-0.2,14000,3500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea6,c(-320,-1.2,42000,10500),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea6,c(-520,-2.0,28000,42000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea6,c(-350,-1.2,19000,25000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea6,c(-320,-0.7,14000,15000),"<=",0,indices = c(1,2,3,4))
add.constraint(lpdea6,c(320,0.7),"=",1,indices = c(1,2))
solve(lpdea6)
get.objective(lpdea6)
get.variables(lpdea6)
#The solution indicates that the objective value is 0.08674521, which indicates that we are not able to achieve maximum efficiency for DMU(6). This happens when we use the weights 0.00162 and 0.00427 for the outputs, 0.1546 and 0.7216 for the input. 

# DEA Analysis
a<-matrix(c(150,400,320,520,350,320,0.2,0.7,1.2,2.0,1.2,0.7),ncol=2)
b<-matrix(c(14000,14000,42000,28000,19000,14000,3500,21000,10500,42000,25000,15000),ncol=2)
colnames(a)<-c("Staff Hours/Day","Supplies/Day")
colnames(b)<-c("Reimbursed Patients/Day","Privately Paid Patients/Day")
rownames(a)<-paste0(rep("Facility",6),seq(1,6,1))
rownames(b)<-paste0(rep("Facility",6),seq(1,6,1))
r1 <-dea(a,b,RTS = "crs")
r2 <-dea(a,b,RTS = "fdh")
r3 <-dea(a,b,RTS = "vrs")
r4 <-dea(a,b,RTS = "irs")
r5 <-dea(a,b,RTS = "drs")
r6 <-dea(a,b,RTS = "add")
r7 <-dea(a,b,RTS = "irs2")
r8 <-dea(a,b,RTS = "fdh+")
r9 <-dea(a,b,RTS = "vrs+")

###Question 2:
#Peers and Lambdas values for each assumption.
peers(r1)
lambda(r1)

# The peer units for DMU(5) are [1,2,4], with relative weights [0.2000000,0.08048142,0.5383307]. Similary for DMU(6), the peer units are [1,2,4], with weights [0.3428571,0.39499264,0.1310751], respectively.

peers(r2)
lambda(r2)
peers(r3)
lambda(r3)
peers(r4)
lambda(r4)
peers(r5)
lambda(r5)
peers(r6)
lambda(r6)
peers(r7)
lambda(r7)
peers(r8)
lambda(r8)
peers(r9)
lambda(r9)

###Question 3:
result <-cbind(round(r1$eff,4),round(r1$lambda,4))
colnames(result)<-c("efficieny",rownames(result))
result
# From the above table, except Facility5 and Facility6 nursing homes remaining nursing homes are efficient.
# The efficiency of these nursing homes can be achieved by using shadow prices (lambda values from the above table, they are the variables related to the constraints limiting the efficiency of each unit to be no greater than 1).

###Question 4
c1<-cbind(r1$eff,r2$eff,r3$eff,r4$eff,r5$eff,r6$eff,r7$eff,r8$eff,r9$eff)
colnames(c1)<-c(paste0(rep("r",9),seq(1,9,1)))
c1
# For each assumption, efficiency of the units have varied

```

